import { Button } from "@/components/ui/button"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { SessionDetail } from "../medical-agent/[sessionId]/page"
import moment from "moment"

export function ViewReport({data}: {data: SessionDetail}) {
    return (
    <div>
      <Dialog>
        <DialogTrigger asChild><Button variant={'outline'} size={'sm'}>View Report</Button></DialogTrigger>
            <DialogContent>
             <DialogHeader>
                                
             <DialogTitle asChild><h2 className="text-center text-xl">AI Voice Agent Report</h2></DialogTitle>
             <DialogDescription asChild>
                <div className="mt-4">
                 <div>
                    <h2 className="text-lg text-blue-500 border-b border-blue-500">Session Info</h2>
                    <p className="mt-2"><span className="font-bold">Doctor</span> - {data.selectedDoctor.specialist}</p>
                     <p><span className="font-bold">user</span> - {data.report.user}</p>
                     <p><span className="font-bold">Consult On</span> - {moment(new Date(data.createdAt)).fromNow()}</p>
                     <p><span className="font-bold">agent</span> - {data.report.agent}</p>
                 </div>

                 <div className="mt-5">
                    <h2 className="text-lg text-blue-500 border-b border-blue-500">User Complaint</h2>
                    <p className="mt-2"><span className="font-bold">basic details</span> - {data.report.chiefComplaint}</p>
                </div>

                  <div className="mt-5">
                    <h2 className="text-lg text-blue-500 border-b border-blue-500">Summary</h2>
                    <p className="mt-2"><span className="font-bold">Doctor</span> - {data.report.summary}</p>
                 </div>

                 <div className="mt-5">
                    <h2 className="text-lg text-blue-500 border-b border-blue-500">Symptoms</h2>
                    <p className="mt-2"><span className="font-bold"></span> - {data.report.symptoms}</p>
                </div>

                <div className="mt-5">
                    <h2 className="text-lg text-blue-500 border-b border-blue-500">Medicines</h2>
                    <p className="mt-2"><span className="font-bold"></span> - {data.report.medicationsMentioned}</p>
                </div>

                <div className="mt-5">
                    <h2 className="text-lg text-blue-500 border-b border-blue-500">recommendations</h2>
                    <p className="mt-2"><span className="font-bold"></span> - {data.report.recommendations}</p>
                </div>

                <div className=" text-sm text-gray-500 text-md font-sans mt-5 border-t border-gray-500">
                    This report was generated by AI Medical Voice Assistant for Information.
                </div>

                </div>
             </DialogDescription>
             </DialogHeader>
            </DialogContent>
        </Dialog>
        </div>
    )
}